---
- name: restart application container
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    image: "{{ docker_image }}:{{ docker_image_tag }}"
    state: started
    restart: true
    restart_policy: "{{ app_restart_policy }}"
    published_ports:
      - "{{ app_port }}:{{ app_port }}"
    env: "{{ app_env }}"
