apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-info-main
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/XriXis/DevOps-Core-Course.git
    targetRevision: lab12
    path: solution/k8s/devops-info-service
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: service.nodePort
          value: "30082"
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
