{{- if .Values.hooks.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "devops-info-service.fullname" . }}-post-install"
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "{{ .Values.hooks.postInstall.weight }}"
    "helm.sh/hook-delete-policy": {{ .Values.hooks.deletePolicy | quote }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "devops-info-service.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-smoke-test
          image: {{ .Values.hooks.image }}
          command:
            - sh
            - -c
            - >
              wget -qO- http://{{ include "devops-info-service.serviceName" . }}:{{ .Values.service.port }}{{ .Values.hooks.postInstall.path }} &&
              sleep 5 &&
              echo "Post-install smoke test passed"
{{- end }}
